### ISSUE TITLE
include file syntax, and 48k or 50k cartridges

### ISSUE THREAD

**Issue by gtoal** [Timu5/vecx-SDL2#1]
#include "emu\e6522.h"
#include "emu\e6809.h"
#include "emu\e8910.h"
#include "emu\edac.h"
#include "emu\vecx.h"

using backslash only works on windows systems, but using forward slash will work on both windows and linux systems.

Also, in vecx.c the cartridge size is limited to 32K but Vectrex cartridges can in theory support up to 50K as the address space for cartridges runs from 0000 to c7ff, and some cartridges are beginning to use that extended space.

121c119
<       else if (address < 0xc800) /* WAS 8000 - updated for 50K carts */
---
>       else if (address < 0x8000)
150c148
<       else if (address < 0xc800) /* was 8000 - updated for 50k carts */
---
>       else if (address < 0x8000)

the declaration of the cartridge space should also be sized appropriately.  Although you are more likely to find cartridges supporting up to c000 (48k) than c800 (50k).  This is regular non-bank-switched memory.  Bank-switch support is a separate issue.

**Comment by Timu5** [comment]
Committed in 0d356d87c97d162c31302a1b73239c38f5dd032f.

**Comment by gtoal** [comment]
Thanks!  But don't forget the declaration of 'cart' in vecx.h:

typedef struct
{
    M6809 CPU;
    VIA6522 VIA;
    AY8910 PSG;
    DACVec DAC;

    uint8_t rom[8192];
    uint8_t cart[32768];
    uint8_t ram[1024];


it also has to be 0xc800.

Thanks.

Graham

**Comment by Timu5** [comment]
You are right, I totally forgot about that.
Fixed in be61152.
